(web) Simplify Paginator
Salz-Team/salz pull request #81
Opened 2024-10-13 23:52 UTC by japorized

This PR redesigns the paginator to be a quite a bit simpler from a
UX perspective. A popup will show up when a `...` button is clicked, and
there will be a numeric input available for users to select a page
number.

This closes #73.

2024-10-16 01:10 UTC, mosiman reviewed
I checked out the branch and ran it locally and I like it!

<img width="1624" alt="image" src="https://github.com/user-attachments/assets/16631014-02bb-4439-8121-3365c16e3ab7">

i did some light QA and didn't find anything egregious

2024-10-16 01:10 UTC, japorized commented on web/src/lib/components/Paginator.svelte
> +  let jumpToPage = (min: number, max: number) => (n: number) => {
Formatted now

2024-10-16 01:10 UTC, mosiman commented
ill try to actually review it later lol

2024-11-27 01:07 UTC, mosiman approved these changes
lgtm

2024-11-27 01:08 UTC, mosiman submitted a review, later dismissed
still looks good to me

2024-12-18 01:10 UTC, Lugarun commented
I noticed some potential bugs:

# Leaderboard Page

Here is a little snafu on the `leaderboard` page:

![2024-12-17-200533_1920x1080_scrot](https://github.com/user-attachments/assets/ecf50473-f0e7-47cb-8884-9863b407afde)

# Matches Page
Here, there is a `...` between 1 and 2 (you also mentioned that it should center 6 on the list):

![2024-12-17-200650_1920x1080_scrot](https://github.com/user-attachments/assets/edfab319-f428-413a-82bf-681881c4b6b2)

Here, 7, 8, and 9 might be missing?

![2024-12-17-200756_1920x1080_scrot](https://github.com/user-attachments/assets/8e19a1d3-4ad9-4917-8060-389fd71f3822)

2025-01-08 00:56 UTC, Lugarun commented
![2025-01-07-195638_3440x2520_scrot](https://github.com/user-attachments/assets/b353dd61-a055-4691-baf5-f219b2caea23)

2025-01-08 01:02 UTC, Lugarun commented
![2025-01-07-200240_3440x2520_scrot](https://github.com/user-attachments/assets/380ac9ea-3096-4979-836c-070ce82bcbd5)

2025-01-08 01:04 UTC, Lugarun requested changes
Here are some things that I noticed:
1. there is a grey ghost over the matches pagination legend
2. when you navigate to 8 on the matches paginator there are 2 10s rendered
3. when you navigate to 3 on the leaderboard you get 2 3s
4. if you put in a number on the paginator search bar and then enter a bunch of random numbers (till overflow), then you get sent to the page of the first digit (or two) that you enter

2025-01-08 02:02 UTC, Lugarun approved these changes
Oh yeah!

2025-01-08 02:43 UTC, mosiman approved these changes
LGTM lets ship it boys

2025-01-08 02:43 UTC, merged